language: node_js
node_js:
  - '10'
  - '8'

before_install:
- npm update

install:
- npm install -g codecov
- npm install

before_script:
- npm install -save-dev jest

script:
- jest
- istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
- codecov
